import { Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, CircleAlert, Eye, FileSearch, Gauge, ShieldCheck, Sparkles } from "lucide-react";
import { Brand, ConfidenceRing, EvidenceChip, StatusBadge } from "@/components/recruitradar";
import { Button } from "@/components/ui/button";

export function LandingPage() {
  return <main className="landing"><header className="landing-nav"><Brand /><nav><a href="#method">How it works</a><a href="#principles">Why evidence</a></nav><div className="flex gap-2"><Button variant="ghost" asChild><Link to="/login">Sign in</Link></Button><Button asChild><Link to="/signup">Start a new role</Link></Button></div></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow-pill"><Sparkles />AI recruitment intelligence</div><h1>Recruit smarter with evidence, not keywords.</h1><p>RecruitRadar turns resumes into explainable, evidence-backed shortlists.</p><div className="flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/signup">Start a new role<ArrowRight /></Link></Button><Button size="lg" variant="outline" asChild><Link to="/roles">View demo</Link></Button></div><div className="hero-proof"><span><CheckCircle2 />Evidence anchored</span><span><ShieldCheck />Blind by default</span><span><Eye />Human reviewed</span></div></div><EvidencePreview /></section>
    <section id="method" className="landing-section"><div className="section-intro"><p className="eyebrow">How it works</p><h2>From an open role to an interview-ready shortlist.</h2><p>Every recommendation traces back to explicit experience, outcomes, and context in the source material.</p></div><div className="process-grid">{[["01","Analyze the brief","Turn the job description into a recruiter-reviewable requirement matrix."],["02","Inspect evidence","Normalize skills, extract proof, and separate signal from unsupported claims."],["03","Decide with context","Compare candidates, inspect gaps, and build targeted interview questions."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="principles" className="principles"><div><p className="eyebrow">Evidence-based matching</p><h2>What a candidate did matters more than what they listed.</h2><p>RecruitRadar gives keyword presence zero scoring weight. Verified outcomes, relevant context, confidence, and gaps drive each explanation.</p></div><div className="principle-list">{[[FileSearch,"Evidence extraction","Ground every match in a source quote."],[CircleAlert,"Noise detection","Flag unsupported claims and keyword stuffing."],[Gauge,"Explainable shortlisting","Show why each candidate ranks where they do."],[ShieldCheck,"Human in the loop","Keep progression decisions with the recruiter."]].map(([Icon,t,d])=>{const C=Icon as typeof FileSearch; return <div key={String(t)}><C /><span><strong>{t as string}</strong><small>{d as string}</small></span></div>})}</div></section>
    <footer><Brand /><p>Recruitment intelligence built for accountable human decisions.</p></footer>
  </main>;
}

function EvidencePreview() { return <div className="evidence-preview"><div className="preview-top"><div><p className="text-xs text-muted-foreground">Senior Frontend Developer</p><p className="font-semibold">Evidence Desk</p></div><StatusBadge status="Analysis complete" /></div><div className="preview-body"><aside><span className="active">Brief</span><span>Pool <b>128</b></span><span>Shortlist <b>8</b></span><span>Compare</span></aside><section><div className="preview-title"><div><p className="font-semibold">Top evidence match</p><small>Candidate 017 · Blind Mode</small></div><ConfidenceRing value={92} /></div><div className="preview-quote">“Led the migration of a 14-app platform to React and TypeScript, improving LCP by 41%.”</div><div className="flex flex-wrap gap-2"><EvidenceChip>React</EvidenceChip><EvidenceChip>TypeScript</EvidenceChip><EvidenceChip>Performance</EvidenceChip></div><div className="preview-requirements"><span>Architecture ownership <StatusBadge status="MATCH" /></span><span>Mentorship scope <StatusBadge status="UNCERTAIN" /></span></div></section><aside className="preview-lens"><Sparkles /><strong>Agent Lens</strong>{["JD analyzed","Evidence extracted","Noise checked","Shortlist ready"].map(x=><span key={x}><CheckCircle2 />{x}</span>)}</aside></div></div>; }