/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoleRoleIdBriefRouteImport } from './routes/_authenticated/role.$roleId.brief'
import { Route as AuthenticatedRoleRoleIdCompareRouteImport } from './routes/_authenticated/role.$roleId.compare'
import { Route as AuthenticatedRoleRoleIdInterviewKitRouteImport } from './routes/_authenticated/role.$roleId.interview-kit'
import { Route as AuthenticatedRoleRoleIdPoolRouteImport } from './routes/_authenticated/role.$roleId.pool'
import { Route as AuthenticatedRoleRoleIdShortlistRouteImport } from './routes/_authenticated/role.$roleId.shortlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoleRoleIdBriefRoute =
  AuthenticatedRoleRoleIdBriefRouteImport.update({
    id: '/role/$roleId/brief',
    path: '/role/$roleId/brief',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleRoleIdCompareRoute =
  AuthenticatedRoleRoleIdCompareRouteImport.update({
    id: '/role/$roleId/compare',
    path: '/role/$roleId/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleRoleIdInterviewKitRoute =
  AuthenticatedRoleRoleIdInterviewKitRouteImport.update({
    id: '/role/$roleId/interview-kit',
    path: '/role/$roleId/interview-kit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleRoleIdPoolRoute =
  AuthenticatedRoleRoleIdPoolRouteImport.update({
    id: '/role/$roleId/pool',
    path: '/role/$roleId/pool',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleRoleIdShortlistRoute =
  AuthenticatedRoleRoleIdShortlistRouteImport.update({
    id: '/role/$roleId/shortlist',
    path: '/role/$roleId/shortlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/role/$roleId/brief': typeof AuthenticatedRoleRoleIdBriefRoute
  '/role/$roleId/compare': typeof AuthenticatedRoleRoleIdCompareRoute
  '/role/$roleId/interview-kit': typeof AuthenticatedRoleRoleIdInterviewKitRoute
  '/role/$roleId/pool': typeof AuthenticatedRoleRoleIdPoolRoute
  '/role/$roleId/shortlist': typeof AuthenticatedRoleRoleIdShortlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/role/$roleId/brief': typeof AuthenticatedRoleRoleIdBriefRoute
  '/role/$roleId/compare': typeof AuthenticatedRoleRoleIdCompareRoute
  '/role/$roleId/interview-kit': typeof AuthenticatedRoleRoleIdInterviewKitRoute
  '/role/$roleId/pool': typeof AuthenticatedRoleRoleIdPoolRoute
  '/role/$roleId/shortlist': typeof AuthenticatedRoleRoleIdShortlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/role/$roleId/brief': typeof AuthenticatedRoleRoleIdBriefRoute
  '/_authenticated/role/$roleId/compare': typeof AuthenticatedRoleRoleIdCompareRoute
  '/_authenticated/role/$roleId/interview-kit': typeof AuthenticatedRoleRoleIdInterviewKitRoute
  '/_authenticated/role/$roleId/pool': typeof AuthenticatedRoleRoleIdPoolRoute
  '/_authenticated/role/$roleId/shortlist': typeof AuthenticatedRoleRoleIdShortlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/roles'
    | '/settings'
    | '/role/$roleId/brief'
    | '/role/$roleId/compare'
    | '/role/$roleId/interview-kit'
    | '/role/$roleId/pool'
    | '/role/$roleId/shortlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/roles'
    | '/settings'
    | '/role/$roleId/brief'
    | '/role/$roleId/compare'
    | '/role/$roleId/interview-kit'
    | '/role/$roleId/pool'
    | '/role/$roleId/shortlist'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/role/$roleId/brief'
    | '/_authenticated/role/$roleId/compare'
    | '/_authenticated/role/$roleId/interview-kit'
    | '/_authenticated/role/$roleId/pool'
    | '/_authenticated/role/$roleId/shortlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/$roleId/brief': {
      id: '/_authenticated/role/$roleId/brief'
      path: '/role/$roleId/brief'
      fullPath: '/role/$roleId/brief'
      preLoaderRoute: typeof AuthenticatedRoleRoleIdBriefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/$roleId/compare': {
      id: '/_authenticated/role/$roleId/compare'
      path: '/role/$roleId/compare'
      fullPath: '/role/$roleId/compare'
      preLoaderRoute: typeof AuthenticatedRoleRoleIdCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/$roleId/interview-kit': {
      id: '/_authenticated/role/$roleId/interview-kit'
      path: '/role/$roleId/interview-kit'
      fullPath: '/role/$roleId/interview-kit'
      preLoaderRoute: typeof AuthenticatedRoleRoleIdInterviewKitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/$roleId/pool': {
      id: '/_authenticated/role/$roleId/pool'
      path: '/role/$roleId/pool'
      fullPath: '/role/$roleId/pool'
      preLoaderRoute: typeof AuthenticatedRoleRoleIdPoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/$roleId/shortlist': {
      id: '/_authenticated/role/$roleId/shortlist'
      path: '/role/$roleId/shortlist'
      fullPath: '/role/$roleId/shortlist'
      preLoaderRoute: typeof AuthenticatedRoleRoleIdShortlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedRoleRoleIdBriefRoute: typeof AuthenticatedRoleRoleIdBriefRoute
  AuthenticatedRoleRoleIdCompareRoute: typeof AuthenticatedRoleRoleIdCompareRoute
  AuthenticatedRoleRoleIdInterviewKitRoute: typeof AuthenticatedRoleRoleIdInterviewKitRoute
  AuthenticatedRoleRoleIdPoolRoute: typeof AuthenticatedRoleRoleIdPoolRoute
  AuthenticatedRoleRoleIdShortlistRoute: typeof AuthenticatedRoleRoleIdShortlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedRoleRoleIdBriefRoute: AuthenticatedRoleRoleIdBriefRoute,
  AuthenticatedRoleRoleIdCompareRoute: AuthenticatedRoleRoleIdCompareRoute,
  AuthenticatedRoleRoleIdInterviewKitRoute:
    AuthenticatedRoleRoleIdInterviewKitRoute,
  AuthenticatedRoleRoleIdPoolRoute: AuthenticatedRoleRoleIdPoolRoute,
  AuthenticatedRoleRoleIdShortlistRoute: AuthenticatedRoleRoleIdShortlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
